//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portem.MyDateBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsPortem1
    {
        public int ID { get; set; }
        public string Head { get; set; }
        public string ContentText { get; set; }
        public int Preority { get; set; }
    }
}
